Catch 4byte chars without thc
widelands/widelands-website pull request #409
Opened 2022-12-26 09:50 UTC by frankystone

pretty the same as #408 but without a check for threadedcomments, because it needs some more work.

2022-12-26 10:49 UTC, blotter commented on mainpage/urls.py
> +    ),
wenn ich über die Profil Seite eines Benutzers auf Send PM gehe wird der ausgewählte Benutzer nicht im Input übergeben

2022-12-26 11:06 UTC, frankystone commented on mainpage/urls.py
> +    ),
sollte gefixt sein.

Danke fürs testen!

2022-12-26 17:48 UTC, blotter commented on django_messages_wl/forms.py
> +        self.fields["body"].validators.append(check_utf8mb3)
es muss auch die überschrift, ggf der benutzername geprüft werden.

2022-12-27 17:49 UTC, blotter requested changes

2022-12-27 17:49 UTC, blotter commented on pybb/forms.py
from mainpage.validators import virus_scan, check_utf8mb3

??

2022-12-27 17:49 UTC, blotter commented on mainpage/urls.py
> +
für zweil zeilen zwischen etwas oder wofür die neue zeile?

2022-12-27 17:53 UTC, frankystone commented on pybb/forms.py
Geschmackssache, imho.

2022-12-27 17:54 UTC, frankystone commented on mainpage/urls.py
> +
Beim editieren wohl übrig geblieben

2022-12-27 18:01 UTC, blotter approved these changes

2022-12-27 18:01 UTC, merged